### ISSUE TITLE
Sidebar Invisible/Unusable

### ISSUE THREAD

**Issue by codejedi365** [devildant/OctoPrint-ShutdownPrinter#11]
Hey there @devildant, 

Your plugin seems to collide with the DragonOrder 0.1.2 Plugin (@jneilliii) for re-arranging/sticking tabs.  The sidebar window can collapse and uncollapse but the "shutdown when finished" checkbox is not visible.  

I dived in a little bit and found that an extra ".collapse" class is causing the error when added to the "div#sidebar_plugin_shutdownprinter.input-group"  When this class is removed, it returns to normal and clicking the title collapses/uncollapses like normal.  I'm not sure how DragonOrder works but I know there is an class="accordion-body collapse" and "<id>_wrapper" that seems to be at its core.  

I post this to your repository because I don't have any other plugin sidebars that go blank like yours.  My guess at the moment is it has to do with your main <div> using an #id field.  The other sidebars like "Octoklipper" and "Filament Manager" do not use a #id field and instead use distinct (or none) class names for their inner content.  

@jneilliii, I tagged you here as well you can chime in on how your design interacts with a generic sidebar element.  It could be a fix on your end by forcefully removing any #id attributes when you duplicate & wrap the sidebars. 

All these are my preliminary findings and educated guesses and hope it is a helpful place to start.

Thanks to both of you for the great plugins!

**Comment by devildant** [comment]
Hello, 
I have no problem on my side with the plugin DragonOrder and the collapse, the problem with the checkbox is already fixed on the branch master (I expect the return of some user before release), can you try this version : 
https://github.com/devildant/OctoPrint-ShutdownPrinter/archive/master.zip

**Comment by codejedi365** [comment]
@devildant, interesting.. so it happens yesterday, I got the latest release and it updated to the master branch. I still have the issue, I am curious how it is not happening on your side.  I also have TabOrder installed which may play a part in the problem.  

I'm not sure what part you are referring to above.  The window still collapses and opens when clicked and still can be drag and dropped as intended in DragonOrder.  My problem is addressing the fact when I uncollapse the sidebar there is nothing inside the `<div>`.  I expect to see the checkbox but it opens about 4 pixels and thats it.  If you are saying that this part was fixed on master, pip install/upgrade pulls directly from master so it didn't clear up my issue.

**Comment by devildant** [comment]
hello, 
do you use themes for your octoprint?

**Comment by devildant** [comment]
I also installed taborder on my octoprint and my vm test, no problem on both sides.
can you send me the list of your plugin?

**Comment by devildant** [comment]
also I doubt that dragorder, have the least impact, because following a drag and drop it is necessary to clear the cache of your browser, after this refresh forced, it is octoprint that will display the new order, not the plugin dragorder

**Comment by codejedi365** [comment]
![shutdownprinter-sidebar](https://user-images.githubusercontent.com/17354856/50809051-0d279300-12c7-11e9-880c-707c0e2f1cea.png)

@devildant, No I do not use themes for Octoprint.  That is odd to see no error.  I took a snapshot from Google Chrome's Inspector to visually show what I am seeing.  The theory I have for the problem diagnosis starts with the duplicate #id's (green underline).  I estimate the .collapse class (octoprint managed as you mention), is applied to all the div's matching that #id, i.e both.  At this point when clicked the collapse and uncollapse JavaScript functions change the height style attribute (blue arrow) from 0px to auto.  The Red-X, indicates the style modification I change and the sidebar becomes visible as expected.

You probably are correct about DragonOrder.  I can only say I noticed I now lost the visual capability to use shutdownPrinter shortly after I installed DragonOrder, possibly some other plugins (not tab/sidebar styling related), and also the update to Octoprint 1.3.10.

Thanks for your work on this, especially when you can't recreate my issue.  I just tried uninstalling your plugin and re-installing.  It was looked fixed at first.  Now I see why you might not have reproduced the error.  So to reproduce:
1. Click on the Shutdown Printer title to collapse the sidebar
2. Initiate Hard page refresh
3. Now try to uncollapse sidebar.  Errors
NOTE: I do have "remember" is checked in the settings

I was able to cause this error with the above steps with and without the checkbox checked prior to closing.  If I leave the the sidebar uncollapsed and did a hard refresh, it works.  This makes me now think it is potentially adversely mixing with the Stateful Sidebar plugin (which I forgot about).

The list of my plugins are:
Cost Estimation (2.1.2)
CuraEngine (<=15.04)
DeleteAfterPrint Plugin (1.1.1)
**Dragon Order (0.1.2)**
Filament Manager (0.5.3)
Fullscreen Plugin (0.0.4)
GitFiles (1.1.2)
LayerDisplay (0.4.1)
MultipleUpload Plugin (1.0.0)
OctoKlipper (0.2.5)
Octolapse (0.3.4)
Preheat Button (0.2.0)
Print History Plugin (1.2)
PrintTimeGenius Plugin (1.3)
ShutdownPrinter (1.0.1)
Sidebar Temp Graph (0.1.2)
Slicer (1.4.3)
SlicerSettingsParser (2.0.0)
SlicerSettingsTab (1.0.2)
**Stateful Sidebar (0.1.0)
Tab Order (0.5.3)**

**Comment by devildant** [comment]
hello, I reproduce the problem is the Stateful Sidebar plugin (0.1.0) that causes the problem

**Comment by jneilliii** [comment]
That's odd @devildant I'm not aware of that plugin doing anything with IDs, but I'll take a look.

**Comment by devildant** [comment]
@jneilliii , I think it's an unwanted action, it looks like a duplication of the dom element.
I made you an issue for this bug, and another that i detected with the touchUI plugin.
about my plugin, I can correct the problem, but correcting it on your side could avoid unnecessary issues if other plugin uses ids.

**Comment by jneilliii** [comment]
This issue is actually in your jinja template.  The id is duplicated by OctoPrint's core.  You don't need the containing div with that id in your template, it gets added by OctoPrint by default.

If you make your sidebar template like this the issue won't exist...

```
<label class="checkbox">
	<input type="checkbox" data-bind="enable: loginState.isUser(), checked: shutdownprinterEnabled">
	{{ _('Shutdown Printer after print finishes') }}
</label>
```

**Comment by devildant** [comment]
@jneilliii 
without your plugin : 
![image](https://user-images.githubusercontent.com/8700106/50846848-65ff3600-1370-11e9-9d82-90e95d74d0a3.png)

with your plugin : 
![image](https://user-images.githubusercontent.com/8700106/50846974-afe81c00-1370-11e9-8ae6-eb90f4a1e96a.png)

**Comment by jneilliii** [comment]
So was it my plugin or your template creating the duplicate? You closed the ticket so I just want to make sure.

**Comment by devildant** [comment]
@jneilliii  it was to avoid sending the ball back, the most important being the users. I corrected on my side and I released, I did not look at your plugin in detail, but I think I understand the problem, it may be that the name of my identifier is a problem after a collapse, so in doubt, I corrected :)

ps: I mentioned a problem with the plugin touchui in the issue that I opened

**Comment by codejedi365** [comment]
Thanks @devildant & @jneilliii for working together to make the fix!
